### PR TITLE
[G2M] empty data bug fixed

### LINKED ISSUE #43: [BUG] Empty data message is "No columns selected"
**Component Name**
`DataTable`

**Describe the bug**
When data is empty, the table would render `No columns selected` as the placeholder message.

**To Reproduce**
Props that are passed into the component:
```
data = []

<DataTable data={data} />
```

**Expected behavior**
A more descriptive message, such as "Empty data".

**Screenshots**
图片

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: firefox
 - Version: 2.3.2
 - React Version: 16.8

### PR DESCRIPTION
**Pull request by Ethenalee**
fixes #43

### CODE REVIEW

File: src/data-table/index.js [hunk 1]
```diff
@@ -342,7 +342,7 @@ class DataTable extends Component {
               {
                 columns.length === 0 &&
                 <Table.Row textAlign='center'>
-                  <Table.HeaderCell colSpan={columns.length}>{noColumnsMsg}</Table.HeaderCell>
+                  <Table.HeaderCell colSpan={columns.length}>{data.length === 0 ? 'Empty data :(' : noColumnsMsg}</Table.HeaderCell>
```
Comment (woozyking) [inline src/data-table/index.js]: Should we expose this message as one of the configurable props like `emptySearchMsg` and `noColumnsMsg` (but with this current one as default)?

Comment (IYCI) [inline src/data-table/index.js]: we should also handle the case that data is not an array, maybe `(!isArray(data) || data.length === 0)`

Comment (Ethenalee) [reply src/data-table/index.js]: tho if data is not an array it will give an error message before it shows the empty data message
