### PR TITLE
defaultSortDirection, empty results messages, custom sorting templates (fixes don't go here)

### LINKED ISSUE #5: custom sort interface
this would allow much more flexibility for column sortability with a functional interface much similar to the `template` interface

### LINKED ISSUE #7: support default sorting direction

### LINKED ISSUE #8: default empty view

### PR DESCRIPTION
**Pull request by Goondrious**
started with 3 sort functions: 'string', 'date' and 'basic' (which is number)

fixes #5
fixes #7
fixes #8

### CODE REVIEW

**Comment by Goondrious** [comment]
fixes #5 
fixes #7 
fixes  #8

**Comment by IYCI** [comment]
need to remove `.DS_Store` file

File: src/utils/sort.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+        return dirFactor
+      }
+      return 0
+    }
+  case 'basic':
+    return (a,b) => dirFactor*(a-b)
+  default:
+    return (a,b) => dirFactor*(a-b)
+  }
+}
```
Comment (IYCI) [inline src/utils/sort.js]: end of file newline

File: stories/data-table.stories.js [hunk 2]
```diff
@@ -92,3 +110,69 @@ storiesOf('DataTable', module)
...
+          },
+        ]}
+      />
+    </Container>
+  ))
+  .add('Custom sorting', () => (
+    <Container>
+      <DataTable
+        data={monsters}
+        defaultSortKey={'name'}
```
Comment (IYCI) [inline stories/data-table.stories.js]: can directly pass string lile `defaultSortKey='name'`
same as below

File: src/utils/sort.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+      if (aDate < bDate) {
+        return -1*dirFactor
+      }
+      if (aDate > bDate) {
+        return dirFactor
+      }
+      return 0
+    }
+  case 'basic':
+    return (a,b) => dirFactor*(a-b)
```
Comment (woozyking) [inline src/utils/sort.js]: basically spacing before/after operators, as well after comma

```suggestion
    return (a, b) => dirFactor * (a - b)
```

File: src/utils/sort.js [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+  default:
+    return (a,b) => dirFactor*(a-b)
```
Comment (woozyking) [inline src/utils/sort.js]:
```suggestion
    return (a, b) => dirFactor * (a - b)
```

File: src/utils/sort.js [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+        return dirFactor
+      }
+      if (aName > bName) {
+        return -1*dirFactor
+      }
+      return 0
+    }
+  case 'date':
+    return (a,b) => {
+      let aDate = new Date(a)
```
Comment (woozyking) [inline src/utils/sort.js]: `const` here would be fine as we're not reassigning these variables within the scope of this function

File: src/utils/sort.js [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+      if (aName < bName) {
+        return dirFactor
+      }
+      if (aName > bName) {
+        return -1*dirFactor
+      }
+      return 0
+    }
+  case 'date':
+    return (a,b) => {
```
Comment (woozyking) [inline src/utils/sort.js]:
```suggestion
    return (a, b) => {
```

File: src/utils/sort.js [hunk 7]
```diff
@@ -0,0 +1,33 @@
+export default (type, direction) => {
+  let dirFactor = direction === 'ascending' ? 1 : -1
+  switch(type){
+  case 'string':
+    return (a,b) => {
```
Comment (woozyking) [inline src/utils/sort.js]:
```suggestion
    return (a, b) => {
```

File: src/utils/sort.js [hunk 8]
```diff
@@ -0,0 +1,33 @@
+export default (type, direction) => {
+  let dirFactor = direction === 'ascending' ? 1 : -1
+  switch(type){
```
Comment (woozyking) [inline src/utils/sort.js]:
```suggestion
  switch (type) {
```

File: src/data-table/index.js [hunk 9]
```diff
@@ -189,8 +195,13 @@ class DataTable extends Component {
       ? this.getFilteredData()
       : data
 
-    // sorting, todo: remove lodash
-    const sortedData = orderBy(filteredData, [sortColumn], sortDirection.slice(0, -6))
+    const columns = this.pickedColumns()
+
+    const sortedData = sortType ? filteredData.sort(
+      (a,b) => customSort(
```
Comment (woozyking) [inline src/data-table/index.js]:
```suggestion
      (a, b) => customSort(
```

File: src/data-table/index.js [hunk 10]
```diff
@@ -119,6 +124,7 @@ class DataTable extends Component {
       this.setState({
         activePage: 1,
         sortColumn: column,
+        sortType: this.columns().find(col=>col.dataKey===column).sortType,
```
Comment (woozyking) [inline src/data-table/index.js]:
```suggestion
        sortType: this.columns().find(col => col.dataKey === column).sortType,
```

File: src/data-table/index.js [hunk 11]
```diff
@@ -263,7 +272,7 @@ class DataTable extends Component {
                 {columns.map(col => (
                   <Table.HeaderCell
                     key={col.dataKey || col.name}
-                    onClick={this.handleSort(col.dataKey)}
+                    onClick={col.sortable ? this.handleSort(col.dataKey) : ()=>{}}
```
Comment (IYCI) [inline src/data-table/index.js]: you can also return null here

File: src/data-table/data-table-column.js [hunk 12]
```diff
@@ -19,6 +21,8 @@ const defaultProps = {
   format: null,
   template: null,
   nullTemplate: null,
+  sortable: false,
```
Comment (IYCI) [inline src/data-table/data-table-column.js]: maybe set `sortable` to default true here otherwise it would be a breaking change, don't forget to update readme

File: src/data-table/data-table-column.js [hunk 13]
```diff
@@ -19,6 +21,8 @@ const defaultProps = {
...
+  sortType: 'basic',
```
Comment (IYCI) [inline src/data-table/data-table-column.js]: maybe set default `sortType` to string as we mostly use default string sort in snoke and overlord

File: src/data-table/index.js [hunk 14]
```diff
@@ -189,8 +195,13 @@ class DataTable extends Component {
       ? this.getFilteredData()
       : data
 
-    // sorting, todo: remove lodash
-    const sortedData = orderBy(filteredData, [sortColumn], sortDirection.slice(0, -6))
+    const columns = this.pickedColumns()
+
+    const sortedData = sortType ? filteredData.sort(
```
Comment (IYCI) [inline src/data-table/index.js]: looks like `sortType`'s default is not being applied here as the dataTable just refuse to do sort without a `sortType` even if `sortable` is `true`

Comment (IYCI) [reply src/data-table/index.js]: I think i know why this is happening, let me quick make a fix PR
